SELECT scope_id,
       subject_id,
       run_id,
       repo,
       tier,
       workload_count,
       privileged_or_host_workloads,
       rbac_rule_count,
       distinct_rule_triples,
       distinct_cluster_triples,
       cluster_scoped_rules,
       wildcard_rules,
       no_scc_request_recorded,
       flag_secrets_access,
       flag_nodes_access,
       flag_wildcard_verbs,
       flag_wildcard_resources,
       flag_rbac_write,
       flag_pods_exec,
       flag_escalate_bind_impersonate,
       ownership,
       business_unit,
       tree,
       is_branch_audit
FROM operator_privilege
WHERE scope_id IN (SELECT value FROM json_each(:scope_ids))
ORDER BY scope_id, subject_id, repo;
