INSERT INTO report (
    binding_id,
    artifact_digest,
    title,
    metadata,
    executive_summary,
    severity_criteria,
    findings,
    findings_summary,
    remediation_roadmap,
    dependency_audit,
    negative_results,
    asvs_coverage,
    scanner_correlation,
    peach_isolation_review,
    disposition_summary,
    footer
) VALUES (
    :binding_id,
    :artifact_digest,
    :title,
    :metadata,
    :executive_summary,
    :severity_criteria,
    :findings,
    :findings_summary,
    :remediation_roadmap,
    :dependency_audit,
    :negative_results,
    :asvs_coverage,
    :scanner_correlation,
    :peach_isolation_review,
    :disposition_summary,
    :footer
)
ON CONFLICT (binding_id) DO NOTHING;
