INSERT INTO threat_boundary (
    binding_id,
    artifact_digest,
    boundary_key,
    boundary_id,
    subject_id,
    product,
    interface,
    kind,
    exposure,
    complexity,
    privilege,
    encryption,
    authentication,
    connectivity,
    hygiene,
    threat_ids,
    isolation_review_ref
)
VALUES (
    :binding_id,
    :artifact_digest,
    :boundary_key,
    :boundary_id,
    :subject_id,
    :product,
    :interface,
    :kind,
    :exposure,
    :complexity,
    :privilege,
    :encryption,
    :authentication,
    :connectivity,
    :hygiene,
    :threat_ids,
    :isolation_review_ref
)
ON CONFLICT (binding_id, boundary_key) DO NOTHING;
