SELECT scope_id,
       subject_id,
       run_id,
       regression_id,
       title,
       severity,
       cwes,
       cvss,
       locations,
       description,
       remediation,
       evidence,
       attack_pattern,
       category,
       introduced_by,
       routed_id,
       fingerprint,
       fingerprint_algo,
       ownership,
       business_unit,
       tree,
       product,
       is_branch_audit
FROM verification_regression_current
WHERE scope_id IN (SELECT value FROM json_each(:scope_ids))
ORDER BY scope_id, subject_id, regression_id;
