INSERT INTO verification_regression (
    binding_id,
    artifact_digest,
    regression_id,
    title,
    severity,
    cwes,
    cvss,
    locations,
    description,
    remediation,
    evidence,
    attack_pattern,
    category,
    introduced_by,
    routed_id,
    fingerprint,
    fingerprint_algo
)
VALUES (
    :binding_id,
    :artifact_digest,
    :regression_id,
    :title,
    :severity,
    :cwes,
    :cvss,
    :locations,
    :description,
    :remediation,
    :evidence,
    :attack_pattern,
    :category,
    :introduced_by,
    :routed_id,
    :fingerprint,
    :fingerprint_algo
)
ON CONFLICT (binding_id, regression_id) DO NOTHING;
