SELECT scope_id,
       advisory,
       ecosystem,
       module,
       fixed_version,
       vulnerable_range,
       generated_at,
       tiers_executed,
       vulnerable_symbols,
       vulnerable_packages,
       advisory_sources,
       feature_description,
       harness_version,
       options,
       portfolio_graph_db,
       portfolio_graph_version,
       repo,
       classification,
       version,
       direct,
       products,
       binary_linked_library,
       binary_string_scan,
       binary_symbol_scan,
       evidence_level,
       feature_pattern_matches,
       govulncheck,
       govulncheck_trace,
       l1_depends_on,
       l1_version_in_range,
       l4_package_imported,
       l4_packages_found,
       manifest_scan,
       manifest_version,
       needs_manual_trace,
       notes,
       sbom_scan,
       sbom_shipped_version,
       source_import_scan,
       symbol_usage_scan
FROM traust_storage.advisory_exposure
WHERE scope_id IN (
    SELECT jsonb_array_elements_text(%(scope_ids)s::jsonb)
)
ORDER BY scope_id, advisory, classification, repo;
