INSERT INTO traust_storage.doc_variance_record (
    binding_id,
    artifact_digest,
    record_id,
    source_product_slug,
    source_version,
    source_guide,
    source_url,
    source_quote,
    claim,
    code_evidence,
    variance,
    verified_at,
    verified_against,
    disposition,
    disposition_note,
    finding_refs,
    threat_refs
)
VALUES (
    %(binding_id)s,
    %(artifact_digest)s,
    %(record_id)s,
    %(source_product_slug)s,
    %(source_version)s,
    %(source_guide)s,
    %(source_url)s,
    %(source_quote)s,
    %(claim)s,
    %(code_evidence)s,
    %(variance)s,
    %(verified_at)s,
    %(verified_against)s,
    %(disposition)s,
    %(disposition_note)s,
    %(finding_refs)s,
    %(threat_refs)s
)
ON CONFLICT (binding_id, record_id) DO NOTHING;
