INSERT INTO pqc_readiness (
    layer_id,
    project_id,
    artifact_digest,
    title,
    metadata,
    scores,
    flags,
    provenance_summary,
    clock_items,
    readiness_bucket,
    fips_interaction,
    runtime_evidence,
    server_side_caveats,
    notes,
    remediations
) VALUES (
    %(layer_id)s,
    %(project_id)s,
    %(artifact_digest)s,
    %(title)s,
    %(metadata)s,
    %(scores)s,
    %(flags)s,
    %(provenance_summary)s,
    %(clock_items)s,
    %(readiness_bucket)s,
    %(fips_interaction)s,
    %(runtime_evidence)s,
    %(server_side_caveats)s,
    %(notes)s,
    %(remediations)s
)
ON CONFLICT (layer_id) DO UPDATE SET
    project_id = excluded.project_id,
    artifact_digest = excluded.artifact_digest,
    title = excluded.title,
    metadata = excluded.metadata,
    scores = excluded.scores,
    flags = excluded.flags,
    provenance_summary = excluded.provenance_summary,
    clock_items = excluded.clock_items,
    readiness_bucket = excluded.readiness_bucket,
    fips_interaction = excluded.fips_interaction,
    runtime_evidence = excluded.runtime_evidence,
    server_side_caveats = excluded.server_side_caveats,
    notes = excluded.notes,
    remediations = excluded.remediations;
