INSERT INTO remediation (
    layer_id,
    project_id,
    artifact_digest,
    title,
    metadata,
    source_findings,
    fork,
    patch,
    checks,
    revalidation,
    pull_request,
    summary,
    notes,
    footer
) VALUES (
    %(layer_id)s,
    %(project_id)s,
    %(artifact_digest)s,
    %(title)s,
    %(metadata)s,
    %(source_findings)s,
    %(fork)s,
    %(patch)s,
    %(checks)s,
    %(revalidation)s,
    %(pull_request)s,
    %(summary)s,
    %(notes)s,
    %(footer)s
)
ON CONFLICT (layer_id) DO UPDATE SET
    project_id = excluded.project_id,
    artifact_digest = excluded.artifact_digest,
    title = excluded.title,
    metadata = excluded.metadata,
    source_findings = excluded.source_findings,
    fork = excluded.fork,
    patch = excluded.patch,
    checks = excluded.checks,
    revalidation = excluded.revalidation,
    pull_request = excluded.pull_request,
    summary = excluded.summary,
    notes = excluded.notes,
    footer = excluded.footer;
