INSERT INTO report (
    layer_id,
    project_id,
    artifact_digest,
    title,
    metadata,
    executive_summary,
    severity_criteria,
    findings,
    findings_summary,
    remediation_roadmap,
    dependency_audit,
    negative_results,
    asvs_coverage,
    scanner_correlation,
    peach_isolation_review,
    disposition_summary,
    footer
) VALUES (
    %(layer_id)s,
    %(project_id)s,
    %(artifact_digest)s,
    %(title)s,
    %(metadata)s,
    %(executive_summary)s,
    %(severity_criteria)s,
    %(findings)s,
    %(findings_summary)s,
    %(remediation_roadmap)s,
    %(dependency_audit)s,
    %(negative_results)s,
    %(asvs_coverage)s,
    %(scanner_correlation)s,
    %(peach_isolation_review)s,
    %(disposition_summary)s,
    %(footer)s
)
ON CONFLICT (layer_id) DO UPDATE SET
    project_id = excluded.project_id,
    artifact_digest = excluded.artifact_digest,
    title = excluded.title,
    metadata = excluded.metadata,
    executive_summary = excluded.executive_summary,
    severity_criteria = excluded.severity_criteria,
    findings = excluded.findings,
    findings_summary = excluded.findings_summary,
    remediation_roadmap = excluded.remediation_roadmap,
    dependency_audit = excluded.dependency_audit,
    negative_results = excluded.negative_results,
    asvs_coverage = excluded.asvs_coverage,
    scanner_correlation = excluded.scanner_correlation,
    peach_isolation_review = excluded.peach_isolation_review,
    disposition_summary = excluded.disposition_summary,
    footer = excluded.footer;
