INSERT INTO traust_storage.report (
    binding_id,
    artifact_digest,
    title,
    metadata,
    executive_summary,
    severity_criteria,
    findings,
    findings_summary,
    remediation_roadmap,
    dependency_audit,
    negative_results,
    asvs_coverage,
    scanner_correlation,
    peach_isolation_review,
    disposition_summary,
    footer
) VALUES (
    %(binding_id)s,
    %(artifact_digest)s,
    %(title)s,
    %(metadata)s,
    %(executive_summary)s,
    %(severity_criteria)s,
    %(findings)s,
    %(findings_summary)s,
    %(remediation_roadmap)s,
    %(dependency_audit)s,
    %(negative_results)s,
    %(asvs_coverage)s,
    %(scanner_correlation)s,
    %(peach_isolation_review)s,
    %(disposition_summary)s,
    %(footer)s
)
ON CONFLICT (binding_id) DO NOTHING;
