INSERT INTO risk_rating_methodology (
    layer_id,
    project_id,
    artifact_digest,
    methodology,
    methodology_version,
    source,
    documentation,
    schema,
    bands,
    bucket_thresholds,
    likelihood_factors,
    impact_factors,
    matrix,
    fallback,
    threat_intel_factor
) VALUES (
    %(layer_id)s,
    %(project_id)s,
    %(artifact_digest)s,
    %(methodology)s,
    %(methodology_version)s,
    %(source)s,
    %(documentation)s,
    %(schema)s,
    %(bands)s,
    %(bucket_thresholds)s,
    %(likelihood_factors)s,
    %(impact_factors)s,
    %(matrix)s,
    %(fallback)s,
    %(threat_intel_factor)s
)
ON CONFLICT (layer_id) DO UPDATE SET
    project_id = excluded.project_id,
    artifact_digest = excluded.artifact_digest,
    methodology = excluded.methodology,
    methodology_version = excluded.methodology_version,
    source = excluded.source,
    documentation = excluded.documentation,
    schema = excluded.schema,
    bands = excluded.bands,
    bucket_thresholds = excluded.bucket_thresholds,
    likelihood_factors = excluded.likelihood_factors,
    impact_factors = excluded.impact_factors,
    matrix = excluded.matrix,
    fallback = excluded.fallback,
    threat_intel_factor = excluded.threat_intel_factor;
