INSERT INTO traust_storage.verification_regression (
    binding_id,
    artifact_digest,
    regression_id,
    title,
    severity,
    cwes,
    cvss,
    locations,
    description,
    remediation,
    evidence,
    attack_pattern,
    category,
    introduced_by,
    routed_id,
    fingerprint,
    fingerprint_algo
)
VALUES (
    %(binding_id)s,
    %(artifact_digest)s,
    %(regression_id)s,
    %(title)s,
    %(severity)s,
    %(cwes)s,
    %(cvss)s,
    %(locations)s,
    %(description)s,
    %(remediation)s,
    %(evidence)s,
    %(attack_pattern)s,
    %(category)s,
    %(introduced_by)s,
    %(routed_id)s,
    %(fingerprint)s,
    %(fingerprint_algo)s
)
ON CONFLICT (binding_id, regression_id) DO NOTHING;
